version: "3"
services:
  db:
    image: postgres:15
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: $DATABASE_PASSWORD
        POSTGRES_USER: $DATABASE_USER
        POSTGRES_DB: $DATABASE_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: